### ISSUE TITLE
Does it worth it?

### ISSUE THREAD

**Issue by tailhook** [tailhook/trafaret-config#1]
Many of us are using trafaret and yaml for configs but the trafaret's own error reporting was never good enough.

This library is a little big hacky way to add line numbers to the error messages.

Is it cool? Do we need such a library? Is this way is just too ugly? Will it crash on complex trafarets?Should we contribute it to the `trafaret.contrib` instead?

/cc @popravich, @rrader, @axik

**Comment by popravich** [comment]
> Do we need such a library?

yes

> Is this way is just too ugly?
> Will it crash on complex trafarets?

need to take  a deeper look

> Should we contribute it to the `trafaret.contrib` instead?

maybe

**Comment by tailhook** [comment]
Okay, we are going to move the discussion to #2
