### ISSUE TITLE
Release v1.0.0 ?

### ISSUE THREAD

**Issue by tailhook** [tailhook/trafaret-config#2]
Just uploaded to a PyPI version v0.1.0. It supports all built-in trafaret types and should not break on any custom ones. Currently, we are waiting for https://github.com/Deepwalker/trafaret/pull/44 to land (to make certain errors more beautiful), but I don't see any issues with releasing 1.0.0 shortly afterwards.

So everyone is encouraged to try and report any issues. Additional review of API is appreciated.

/cc @popravich, @asvetlov, @axik, @nimnull, @Deepwalker

**Comment by Deepwalker** [comment]
trafaret 0.7.3

**Comment by tailhook** [comment]
That was fast. Thank you, @Deepwalker!

**Comment by tailhook** [comment]
Version `v1.0.0` is released!
