### ISSUE TITLE
support for OrderedDict

### ISSUE THREAD

**Issue by samuelcolvin** [tailhook/trafaret-config#4]
Is it possible to parse a yaml file converting mappings to `OrderedDict`s to preserve the order from the original yaml file?

Example of using `OrderedDict` with yaml loader [here](http://stackoverflow.com/questions/5121931/in-python-how-can-you-load-yaml-mappings-as-ordereddicts).

**Comment by tailhook** [comment]
It's definitely possible. But what stops me is that semantically in YAML it should not matter.

I.e. if you have a tool, that edits the configuration file (for example one like `git config`) it may store keys back in different order.

And even without that, if I as a user of your program edit the configuration file I assume that I may reorder keys anywhere for readability or somesuch. And I always assume that it doesn't change the semantics of configured application.

If order of your keys matters somewhere the canonical way of specifying it in yaml is:

```
- key: value
- key2: value2
```

So we might  want to support this syntax better instead.

**Comment by samuelcolvin** [comment]
I understand what you mean, I agree that in general if you have a dictionary where order matters, it's a pretty good indicator that something has gone wrong.

Thinking about this I can easily find another way round the problem in my case.
