### ISSUE TITLE
Environment variables evaluation support in yml

### ISSUE THREAD

**Issue by gyermolenko** [tailhook/trafaret-config#6]
It’s possible to use environment variables to populate values inside a trafaret config file?
I mean like that:
`setting_name: ${VAR}`

**Comment by tailhook** [comment]
Currently, there is no such support.

Talking about whether there will be such support in the future, or if I accept such PRs. I'm not entirely sure it makes much sense. In the past I've used such style config a lot and this is kinda convenient. But in the later extension, it required not just variable names but also expressions like `${BASE_PORT+1}` which makes config too programmatic.

In my new projects I usually do clear separation of configuration in text file and commonly changed parameters like `--port` and later one is always passed as a command-line parameter (or you can use `default=os.environ.get('VAR')` trick with argparse, or there is a built-in way in `click`). So I'm more or less hesitant to add it.

This also adds complexity for users as sometimes '${` might be useful in config as raw text, and may provide a security issue if it's a tool dealing with third-party configs.

On the other hand, I think it's easy to make a subclass of `trafaret.String` and do substitution there. It may even work with other scalars like `MyString() | trafaret.Int()` but I'm not sure about latter.

**Comment by gyermolenko** [comment]
Hi, thanks for answering.
Do you use different dev.yml / prod.yml / test.yml files per environment and then pass --magic-flag="prod" when initializing app? 
Or do you pass every setting as a command-line parameter? In that case I don't think you need trafaret_config at all, since it is not used in this scenario.

**Comment by tailhook** [comment]
Usually, there are different dev/prod configs. And `--port` is used for example for tests to pass random port. Or on deployment system where it's only known at runtime (i.e. there are just a few command-line params).   Also logging is tweaked with CLI/env.

**Comment by gyermolenko** [comment]
And you keep them in .gitignore? (as you would keep .env files with passwords?)

**Comment by tailhook** [comment]
Usually, we have a separate config with secrets (actually a dir, where also keys and certificates a relocated). And usually, development config is kept in git, because it's not secret (plain simple passwords for services running on localhost).

**Comment by tailhook** [comment]
Implemented in master. Currently it's in `trafaret-config==2.0.0b2`. Will release 2.0 shortly.

**Comment by tailhook** [comment]
2.0.0 released!
